### PR TITLE
Wip parser in scalajs

### PR DESCRIPTION
**Pull request by mrerrormessage**
[Review on Reviewable](https://reviewable.io/reviews/netlogo/netlogo-headless/34)

### CODE REVIEW

**Comment by SethTisue** [comment]
(not actually ready for merge yet. I just suggested Robert make a PR anyway in case any discussion is needed. we had a hangout about it today.)

**Comment by mrerrormessage** [comment]
Note that Travis is failing due to submodule problems. I would like to sit down with @TheBizzle and discuss this at whatever point you're ready. The only merge conflict is in build.sbt and is regarding the NetLogoHeadless/NetLogoHeadlessMaven change you made a week ago. Is that a permanent change, or was it just for a period of time? It isn't hard for me to update the branch, just let me know. Also, the Travis CI build is failing because the submodules moved. Any guesses on how to get Travis back in a good state?

**Comment by TheBizzle** [comment]
> Also, we'll need a new bintray repository for the parserJs artifact

I've created a place in the NetLogoHeadless BinTray repository for [a 'parser-js' project](https://bintray.com/netlogo/NetLogoHeadless/parser-js/view).  I believe that the parser's subproject's `name` in SBT will need to be set to `"parser-js"` so the SBT BinTray plugin will send the artifact to the right spot.

**Comment by TheBizzle** [comment]
Could we get some documentation that explains how you're supposed to use this behemoth of a project?—how to get the artifacts out of it and what to expect to find in each artifact?

**Comment by mrerrormessage** [comment]
Thanks for creating the bintray repository! I will work on putting together some documentation together.

**Comment by TheBizzle** [comment]
What's with all the compilation errors in `parser-core` at the beginning of the build?  I see this both [on Travis](https://travis-ci.org/NetLogo/NetLogo-Headless/builds/53826562) and when I try to build the project locally with `nightly.sh`.

**Comment by mrerrormessage** [comment]
The errors have been fixed with the latest push.

**Comment by TheBizzle** [comment]
Is it intentional that `/src/main/prim/etc/_netlogoweb.scala` is the only file in `/src`, or is this file misplaced?

Once that situation is addressed, this can be merged.

**Comment by mrerrormessage** [comment]
I'll move `_netlogoweb` over. I thought I had everything, but apparently not

**Pull request merged**
