### PR TITLE
the great compiler refactoring of 2013–2014

### PR DESCRIPTION
**Pull request by mrerrormessage**
as described in detail over at https://github.com/NetLogo/NetLogo/wiki/Compiler-Refactoring-Notes

[Review on Reviewable](https://reviewable.io/reviews/netlogo/netlogo-headless/22)

### CODE REVIEW

**Comment by SethTisue** [comment]
LGTM

**Comment by TheBizzle** [comment]
This needs another rebase, given the new state of `master`.

There will be merge conflicts.

**Comment by mrerrormessage** [comment]
I'll rebase this afternoon.

**Comment by SethTisue** [comment]
😃

**Comment by SethTisue** [comment]
January 8, 2015: a cold day in hell

**Pull request merged**
